### ISSUE TITLE
CSV upload for team definition

### ISSUE THREAD

**Issue by vpieterse** [MatthiasHarvey/pinocchio#199]

**Comment by egeldenhuys** [comment]
#### TODO
- [X] Import code from user admin
- [ ] Adapt code to teams
- [ ] Validate CSV
- [ ] Display errors to user after initial submit (Round does not exist, user does not exist)
- [ ] Display pending transactions
- [ ] Confirm CSV and apply pending transaction.
